#--------------------------------#
#    environment configuration   #
#--------------------------------#
nuget:
  project_feed: true

#--------------------------#
#    build configuration   #
#--------------------------#
before_build:
  - nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true

#-------------------------------#
#    deployment configuration   #
#-------------------------------#
deploy:
  provider: NuGet
  api_key:
    secure: rGnzrQ4lRcTN4BXSukxZBNlIi5UKi9d92cnQwRH29Re/xff8muk63Yb3f+DXSXAH
  skip_symbols: false
  on:
    appveyor_repo_tag: true		# Only deploy packages when a tag is pushed